#!/usr/bin/env python

"""
jdasm: Java disassembler (prototype)

Usage:
    jdasm [-d] [-r] [-l <logfile>] [-o <fname>] [<classfile> ...]

Options:
    -h  --help         Show this screen.
    --version          Show version.
    -r                 Roundtrip format.
    -o <fname>         Set output filename.
    -d                 Print debug info to log file.
    -l <logfile>       Set logfilename [default: LOG.txt]
"""

import os
import docopt  # type:ignore

from Globals import g
from log import Log
import classfile
import util

VERSION = '0.0.1'
MAX_CLASSFILE_SIZE = 50_000  # Refuse to do anything bigger.


def main() -> None:
    g.args = docopt.docopt(__doc__, version=VERSION)
    print(g.args)
    if g.args['-d']:
        g.debug = True
        g.log = Log(g.args['-l'])
        g.log.log('jdasm version', VERSION)
    else:
        g.debug = False

    for f in g.args['<classfile>']:
        if g.debug:
            g.log.log('class:', f)
        do_classfile(f)
    if g.debug:
        g.log.close()


def do_classfile(fname: str) -> None:
    if not os.path.isfile(fname):
        util.fatal(fname, 'is not a file')
    size = os.stat(fname).st_size
    if size == 0 or size > MAX_CLASSFILE_SIZE:
        util.fatal(fname, 'is empty or too big')
    with open(fname, 'rb') as f:
        buff = f.read()
    if g.debug:
        g.log.log(fname, 'file size =', len(buff))
    if buff[0:4] != bytes([0xca, 0xfe, 0xba, 0xbe]):
        util.fatal(fname, 'is not a class file')

    cls = classfile.parse(buff)
    if cls:
        if g.args['-o']:
            outfile = g.args['-o']
        else:
            outfile = util.gen_output_file_name(fname)
        print('output:', outfile)
        classfile.disassemble(cls, outfile)
    else:
        util.fatal('unable to parse file', fname)


if __name__ == '__main__':
    main()
